simplify and change func name
codwu/tsdb pull request #1
Opened 2018-05-23 14:35 UTC by krasi-georgiev

added explicit func name for adding an internal to an existing tombstone.
simplified on few places.

Signed-off-by: Krasi Georgiev <kgeorgie@redhat.com>

2018-05-27 05:36 UTC, codwu requested changes
@krasi-georgiev

2018-05-27 05:36 UTC, codwu commented on block.go
> +				stones.addInterval(p.At(), Interval{tmin, tmax})
why do you use `addInterval()` ? According to the origin code, it should be `put()` here.

2018-05-27 10:47 UTC, krasi-georgiev commented on block.go
> +				stones.addInterval(p.At(), Interval{tmin, tmax})
good catch , I was trying few things and must have messed up this one.
Update

2018-05-29 12:01 UTC, codwu approved these changes

2018-05-29 12:01 UTC, merged